In [4]:
import numpy as np #수치 계산을 위한 라이브러리
import addcopyfighandler #복사 붙여 넣기 등의 기능 가능
import matplotlib.pyplot as plt # 그래프 그리기 위한 라이브러리
import mne #뇌파 데이터 분석을 위한 라이브러리

In [ ]:
sample_data_folder = mne.datasets.sample.data_path() # 폴더 경로 설정
sample_data_raw_file = sample_data_folder / "MEG" / "sample" / "sample_audvis_raw.fif"
# raw 데이터 파일 경로 설정
raw = mne.io.read_raw_fif(sample_data_raw_file) # raw 데이터 설정
raw.crop(tmax=60).load_data() # raw 데이터 자르고(61초까지) 로드

Opening raw data file C:\Users\user\mne_data\MNE-sample-data\MEG\sample\sample_audvis_raw.fif...
    Read a total of 3 projection items:
        PCA-v1 (1 x 102)  idle
        PCA-v2 (1 x 102)  idle
        PCA-v3 (1 x 102)  idle
    Range : 25800 ... 192599 =     42.956 ...   320.670 secs
Ready.
Reading 0 ... 36037  =      0.000 ...    60.000 secs...


<Raw | sample_audvis_raw.fif, 376 x 36038 (60.0 s), ~106.6 MiB, data loaded>

In [5]:
raw.copy().pick(picks="stim").plot(start = 3, duration = 6) 
# raw 데이터 복사해서 stim(자극) 채널만 선택해서 3초부터 6초 동안(9초까지)의 데이터를 그래프로 그리기

Using qt as 2D backend.


Channels marked as bad:
none


In [7]:
events = mne.find_events(raw, stim_channel = "STI 014")
#raw 데이터에서 stim channel 중 summation channel "STI 014"에서 이벤트 찾기
print(events[:5])
# 찾은 이벤트 중 처음 5개 출력

Finding events on: STI 014
86 events found on stim channel STI 014
Event IDs: [ 1  2  3  4  5 32]
[[27977     0     2]
 [28345     0     3]
 [28771     0     1]
 [29219     0     4]
 [29652     0     2]]


In [9]:
testing_data_folder = mne.datasets.testing.data_path() # 폴더 경로 설정
eeglab_raw_file = testing_data_folder / "EEGLAB" / "test_raw.set"
# raw 데이터 파일 경로 설정
eeglab_raw = mne.io.read_raw_eeglab(eeglab_raw_file) # raw 데이터 설정
print(eeglab_raw.annotations) # raw 데이터의 annotations(주석) 출력

Reading C:\Users\user\mne_data\MNE-testing-data\EEGLAB\test_raw.fdt
<Annotations | 154 segments: rt (74), square (80)>


In [10]:
print(len(eeglab_raw.annotations))
# raw 데이터의 annotations(주석) 개수 출력
print(set(eeglab_raw.annotations.duration))
# raw 데이터의 annotations(주석) 지속 시간 출력
print(set(eeglab_raw.annotations.description))
# raw 데이터의 annotations(주석) 설명 출력
print(eeglab_raw.annotations.onset[0])
# raw 데이터의 첫 번째 annotations(주석) 시작 시간 출력

154
{np.float64(0.0)}
{np.str_('rt'), np.str_('square')}
1.000068


In [12]:
events_from_annot, event_dict = mne.events_from_annotations(eeglab_raw)
# raw 데이터의 annotations(주석)에서 이벤트 추출하기
print(event_dict)
# 추출한 event의 array 출력 array의 설명과 정수 ID 매핑
print(events_from_annot[:5])
# 추출한 이벤트 중 처음 5개 출력
# onset으로 1열 duration으로 2열 description으로 3열

Used Annotations descriptions: [np.str_('rt'), np.str_('square')]
{np.str_('rt'): 1, np.str_('square'): 2}
[[128   0   2]
 [217   0   2]
 [267   0   1]
 [602   0   2]
 [659   0   1]]
